# Generated by Django 6.0.6 on 2026-06-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_status',
            field=models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='booking_status',
            field=models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован')], default='available', max_length=20),
        ),
    ]
