# Generated by Django 6.0.6 on 2026-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingtools', '0003_room_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат')], default='', max_length=20),
        ),
    ]
