# Generated by Django 6.0.6 on 2026-07-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingtools', '0005_building_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='model_3d_url',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model_3d_url',
        ),
    ]
