# Generated by Django 6.0.6 on 2026-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Новое сообщение'), ('booking_created', 'Новое бронирование'), ('booking_cancelled', 'Отмена бронирования')], default='message', max_length=30),
        ),
    ]
